version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3 